import { makeStyles } from "tss-react/mui";
import { PADDING_GAP_LAYOUT } from "@/utils/constants/style.constant";
import { ATSH_CTA_BUTTON_SIZE, ATSH_HERO_TYPOGRAPHY } from "../_constants/atsh.constants";

const useAtshStyles = makeStyles({ name: "AtshHero" })((theme) => ({
  heroSection: {
    position: "relative",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    width: "100%",
    overflow: "hidden",
    // Background image is mounted at `AtshApp` (fixed), keep sections transparent.
    backgroundColor: "transparent",
    height: "calc(100dvh - var(--atsh-header-height, 0px))",
    minHeight: "calc(100dvh - var(--atsh-header-height, 0px))",
    padding: 0,
    boxSizing: "border-box",
  },
  heroBgLayer: {
    // Keep ATSH cosmic background shared across sections while scrolling.
    // Using fixed positioning so the background stays still and continues behind the spiral section.
    position: "fixed",
    top: 0,
    left: 0,
    width: "100vw",
    height: "100vh",
    backgroundSize: "cover",
    backgroundPosition: "center bottom",
    backgroundRepeat: "no-repeat",
    pointerEvents: "none",
    zIndex: 0,
    [theme.breakpoints.up("md")]: {
      backgroundPosition: "center center",
    },
  },
  heroInner: {
    position: "relative",
    zIndex: 1,
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    width: "100%",
    height: "100%",
    minHeight: 0,
    maxWidth: "100%",
    margin: "0 auto",
    paddingLeft: PADDING_GAP_LAYOUT,
    paddingRight: PADDING_GAP_LAYOUT,
    boxSizing: "border-box",
    [theme.breakpoints.up("md")]: {
      maxWidth: "auto",
    },
    [theme.breakpoints.up("xl")]: {
      maxWidth: 978,
    },
  },
  heroOrbitStage: {
    position: "relative",
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    width: "100%",
    gap: theme.spacing(4),
    [theme.breakpoints.up("md")]: {
      gap: theme.spacing(10),
    },
  },
  heroContentBlock: {
    position: "relative",
    zIndex: 1,
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    width: "100%",
    gap: theme.spacing(2),
    [theme.breakpoints.up("md")]: {
      gap: theme.spacing(4),
    },
  },
  heroLogosStage: {
    position: "relative",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    width: "100%",
    zIndex: 1,
  },
  heroTextStack: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    width: "100%",
    gap: theme.spacing(2),
  },
  heroOrbitAnchor: {
    position: "relative",
    width: "100%",
    height: 0,
    flexShrink: 0,
    zIndex: 0,
  },
  heroOrbitAmbientLayer: {
    position: "absolute",
    top: 0,
    left: "50%",
    transform: "translate(-50%, -50%)",
    pointerEvents: "none",
  },
  heroLogosFloat: {
    position: "relative",
    zIndex: 1,
  },
  collabLogos: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    flexWrap: "nowrap",
    gap: 19,
    width: "auto",
    maxWidth: "100%",
    [theme.breakpoints.up("md")]: {
      gap: 25,
    },
  },
  collabLogoItem: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    overflow: "hidden",
    backgroundColor: "transparent",
    backdropFilter: "none",
    WebkitBackdropFilter: "none",
    flexShrink: 0,
    // Mobile ~52% Figma desktop size from JSON CSS vars.
    width: "calc(var(--atsh-collab-logo-w, 232px) * 0.52)",
    height: "calc(var(--atsh-collab-logo-h, 121px) * 0.52)",
    [theme.breakpoints.up("md")]: {
      width: "var(--atsh-collab-logo-w, 232px)",
      height: "var(--atsh-collab-logo-h, 121px)",
    },
  },
  collabLogoImage: {
    width: "100%",
    height: "100%",
    objectFit: "contain",
    objectPosition: "center",
    display: "block",
  },
  collabX: {
    fontFamily: "var(--font-hanken-grotesk), sans-serif",
    fontWeight: 500,
    fontSize: 12.7,
    lineHeight: 1.5,
    textTransform: "uppercase",
    color: theme.palette.common.white,
    flexShrink: 0,
    [theme.breakpoints.up("md")]: {
      fontSize: 25.06,
    },
  },
  heroHeadline: {
    position: "relative",
    zIndex: 1,
    display: "flex",
    flexDirection: "column",
    justifyContent: "center",
    alignItems: "center",
    gap: 0,
    fontWeight: 400,
    fontSize: ATSH_HERO_TYPOGRAPHY.headline.mobile.fontSize,
    lineHeight: ATSH_HERO_TYPOGRAPHY.headline.mobile.lineHeight,
    color: theme.palette.common.white,
    textAlign: "center",
    width: "100%",
    margin: 0,
    [theme.breakpoints.up("md")]: {
      fontSize: ATSH_HERO_TYPOGRAPHY.headline.tablet.fontSize,
      lineHeight: ATSH_HERO_TYPOGRAPHY.headline.tablet.lineHeight,
    },
    [theme.breakpoints.up("xl")]: {
      fontSize: ATSH_HERO_TYPOGRAPHY.headline.desktop.fontSize,
      lineHeight: ATSH_HERO_TYPOGRAPHY.headline.desktop.lineHeight,
    },
  },
  heroHeadlineLine: {
    display: "flex",
    flexWrap: "wrap",
    justifyContent: "center",
    alignItems: "center",
    columnGap: "0.28em",
    rowGap: 0,
    width: "100%",
  },
  heroHeadlineWord: {
    display: "inline-block",
    whiteSpace: "nowrap",
  },
  heroTitleSubHeadline: {
    textTransform: "capitalize",
  },
  heroTaglineWrap: {
    position: "relative",
    zIndex: 1,
    width: "100%",
    display: "flex",
    flexDirection: "column",
    gap: 8,
    [theme.breakpoints.up("md")]: {
      gap: 16,
    },
  },
  tagline: {
    fontFamily: "var(--font-be-vietnam), sans-serif",
    fontWeight: 400,
    fontSize: ATSH_HERO_TYPOGRAPHY.tagline.mobile.fontSize,
    lineHeight: ATSH_HERO_TYPOGRAPHY.tagline.mobile.lineHeight,
    color: theme.palette.common.white,
    textAlign: "center",
    whiteSpace: "pre-line",
    width: "100%",
    [theme.breakpoints.up("md")]: {
      fontSize: ATSH_HERO_TYPOGRAPHY.tagline.tablet.fontSize,
      lineHeight: ATSH_HERO_TYPOGRAPHY.tagline.tablet.lineHeight,
    },
    [theme.breakpoints.up("xl")]: {
      fontSize: ATSH_HERO_TYPOGRAPHY.tagline.desktop.fontSize,
      lineHeight: ATSH_HERO_TYPOGRAPHY.tagline.desktop.lineHeight,
    },
  },
  ctaRow: {
    position: "relative",
    zIndex: 1,
    display: "flex",
    flexDirection: "row",
    flexWrap: "wrap",
    alignItems: "center",
    justifyContent: "center",
    gap: 12,
    width: "100%",
    [theme.breakpoints.up("sm")]: {
      flexDirection: "row",
      flexWrap: "wrap",
      gap: 16,
    },
    [theme.breakpoints.up("md")]: {
      gap: 24,
    },
  },
  ctaButtonWrap: {
    position: "relative",
    display: "inline-flex",
    alignItems: "stretch",
    flexShrink: 0,
    width: ATSH_CTA_BUTTON_SIZE.mobile.width,
    height: ATSH_CTA_BUTTON_SIZE.mobile.height,
    [theme.breakpoints.up("md")]: {
      width: ATSH_CTA_BUTTON_SIZE.desktop.width,
      height: ATSH_CTA_BUTTON_SIZE.desktop.height,
    },
  },
  ctaButton: {
    "&&": {
      fontFamily: "var(--font-be-vietnam), sans-serif",
      fontWeight: 700,
      fontSize: ATSH_HERO_TYPOGRAPHY.cta.mobile.fontSize,
      lineHeight: ATSH_HERO_TYPOGRAPHY.cta.mobile.lineHeight,
      flex: "0 0 auto",
      width: "100%",
      height: "100%",
      minWidth: "unset",
      maxWidth: "none",
      boxSizing: "border-box",
      textTransform: "none",
      padding: 0,
      minHeight: 0,
      boxShadow: "none",
      whiteSpace: "nowrap",
      display: "inline-flex",
      alignItems: "center",
      justifyContent: "center",
      [theme.breakpoints.up("md")]: {
        fontSize: ATSH_HERO_TYPOGRAPHY.cta.desktop.fontSize,
        lineHeight: ATSH_HERO_TYPOGRAPHY.cta.desktop.lineHeight,
      },
    },
  },
  ctaPrimary: {
    "&&": {
      color: theme.palette.common.white,
      backgroundColor: "transparent",
      "&:hover": {
        backgroundColor: "transparent",
        backgroundImage: "none",
      },
    },
  },
  ctaSecondary: {
    "&&": {
      color: theme.palette.common.white,
      backgroundColor: "transparent",
      "&:hover": {
        backgroundColor: "transparent",
        backgroundImage: "none",
      },
    },
  },
  ctaLabel: {
    display: "inline-flex",
    position: "relative",
    zIndex: 1,
    alignItems: "center",
    justifyContent: "center",
  },
  ctaLabelChar: {
    display: "inline-block",
    whiteSpace: "pre",
  },
}));

export default useAtshStyles;
