import { makeStyles } from "tss-react/mui";
import { TYPOGRAPHY_STYLES } from "@/utils/constants/typography.constant";

const useStyles = makeStyles()((theme) => ({
  userPopupPaper: {
    padding: "20px",
    backgroundColor: "#FFFFFF",
    borderRadius: "0px",
    boxShadow: "0px 4px 20px rgba(0, 0, 0, 0.1)",
    width: "276px",
    overflow: "hidden",
    border: "1px solid #DDD",
  },
  userPopupButton: {
    ...TYPOGRAPHY_STYLES.base.regular,
    color: "#FFFFFF",
    backgroundColor: "#27251F",
    padding: "8px 12px",
    borderRadius: "0px",
    border: "none",
    cursor: "pointer",
    width: "100%",
    textAlign: "center",
    transition: "opacity 0.2s ease",
    "&:hover": {
      opacity: 0.9,
    },
  },
  userPopupText: {
    ...TYPOGRAPHY_STYLES.sm.bold,
    color: "#27251F",
    textAlign: "center",
    lineHeight: "1.5",
  },
  userDrawerPaper: {
    width: "450px",
    height: "100%",
    display: "flex",
    flexDirection: "column",
    overflow: "hidden",
    [theme.breakpoints.down("lg")]: {
      width: "50%",
    },
    [theme.breakpoints.down("md")]: {
      width: "100%",
    },
  },
  userDrawerHeader: {
    flexShrink: 0,
    padding: "16px 20px",
    borderBottom: "1px solid #F5F5F5",
  },
  userDrawerName: {
    ...TYPOGRAPHY_STYLES.xl.bold,
    color: "#27251F",
  },
  userDrawerBadge: {
    ...TYPOGRAPHY_STYLES.md.bold,
    color: "#27251F",
    backgroundColor: "#EEEEEF",
    padding: "2px 12px",
    borderRadius: "20px",
    marginLeft: "8px",
  },
  userDrawerPoints: {
    display: "flex",
    alignItems: "center",
    gap: "8px",
    marginTop: "4px",
  },
  userDrawerPointsText: {
    ...TYPOGRAPHY_STYLES.base.regular,
    color: "#27251F",
  },
  userDrawerContent: {
    padding: "16px 20px",
    flex: 1,
    minHeight: 0,
    overflowY: "auto",
  },
  userDrawerClose: {
    cursor: "pointer",
    color: "#27251F",
  },
  pointsCard: {
    background: "linear-gradient(135deg, #F9FFF0 0%, #FFFFFF 100%)",
    borderRadius: "12px",
    padding: "20px",
    position: "relative",
    overflow: "hidden",
    border: "1px solid #E5E7EB",
    marginBottom: "24px",
  },
  pointsCardTitle: {
    ...TYPOGRAPHY_STYLES.xs.regular,
    color: "#71717A",
    marginBottom: "4px",
  },
  pointsCardValue: {
    ...TYPOGRAPHY_STYLES.xl.bold,
    color: "#27251F",
    display: "flex",
    alignItems: "center",
    gap: "8px",
  },
  levelSection: {
    display: "flex",
    justifyContent: "space-between",
    marginTop: "20px",
    position: "relative",
  },
  levelItem: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    gap: "4px",
    zIndex: 1,
  },
  levelLabel: {
    ...TYPOGRAPHY_STYLES.xs.bold,
    padding: "4px 12px",
    borderRadius: "20px",
    backgroundColor: "#F4F4F5",
    color: "#71717A",
  },
  levelLabelActive: {
    backgroundColor: "#FDE047",
    color: "#27251F",
  },
  levelProgressLine: {
    position: "absolute",
    top: "10px",
    left: "20px",
    right: "20px",
    height: "2px",
    backgroundColor: "#E5E7EB",
    zIndex: 0,
  },
  levelProgressFill: {
    height: "100%",
    backgroundColor: "#27251F",
    width: "30%",
  },
  actionGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(4, 1fr)",
    gap: "16px",
  },
  actionItem: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    gap: "16px",
    padding: "8px",
    cursor: "pointer",
  },
  actionIconWrapper: {
    width: 48,
    height: 48,
    backgroundColor: "#F5F5F5",
    borderRadius: "50%",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    position: "relative",
  },
  actionBadge: {
    position: "absolute",
    top: -2,
    right: -4,
    minWidth: 20,
    height: 20,
    padding: "0 4px",
    borderRadius: "100px",
    backgroundColor: "#E5E7EB",
    color: "#000",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    ...TYPOGRAPHY_STYLES.sm.regular,
  },
  actionLabel: {
    ...TYPOGRAPHY_STYLES.sm.regular,
    color: "#27251F",
    textAlign: "center",
  },
  accountButton: {
    width: "100%",
    border: "none",
    backgroundColor: "#0A0A0A",
    color: "#FFFFFF",
    padding: "12px 16px",
    cursor: "pointer",
    textAlign: "center",
    textTransform: "capitalize",
    ...TYPOGRAPHY_STYLES.md.bold,
    "&:hover": {
      opacity: 0.95,
    },
  },
}));

export default useStyles;
