import { makeStyles } from "tss-react/mui";
import { TYPOGRAPHY_STYLES } from "@/utils/constants/typography.constant";

const useStyles = makeStyles()((theme) => ({
  root: {
    width: "100%",
    boxSizing: "border-box",
    gap: "12px",
    padding: "16px",
    backgroundColor: "#F8F8F8",
    borderRadius: "6px",
  },
  header: { display: "flex", gap: "12px", minWidth: 0 },
  imageWrapper: {
    width: 62,
    height: 62,
    position: "relative",
    flexShrink: 0,
    backgroundColor: "var(--product-image-background)",
    border: "1px solid #DEDEDE",
    borderRadius: "5px",
    boxSizing: "border-box",
  },
  image: { width: "100%", height: "100%", objectFit: "cover", borderRadius: "5px" },
  quantityBadge: {
    position: "absolute",
    top: "-10px",
    right: "-8px",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    minWidth: "21px",
    height: "21px",
    padding: "0 4px",
    boxSizing: "border-box",
    borderRadius: "4px",
    backgroundColor: "#707070",
    color: "#FFFFFF",
    ...TYPOGRAPHY_STYLES.sm.regular,
    lineHeight: "21px",
    whiteSpace: "nowrap",
    zIndex: 2,
  },
  details: { minWidth: 0, flex: 1, gap: "6px" },
  name: { ...TYPOGRAPHY_STYLES.base.bold, color: "#27272A" },
  price: { ...TYPOGRAPHY_STYLES.base.bold, color: "#27272A", whiteSpace: "nowrap" },
  originalPrice: { ...TYPOGRAPHY_STYLES.sm.regular, color: "#9DA3AE", textDecoration: "line-through" },
  components: { gap: "8px" },
  component: {
    display: "flex",
    gap: "16px",
    padding: "8px 16px",
    backgroundColor: "#FFFFFF",
    borderRadius: "6px",
    width: "100%",
    boxSizing: "border-box",
  },
  componentImageWrapper: {
    width: 46,
    height: 46,
    flexShrink: 0,
    backgroundColor: "var(--product-image-background)",
    border: "1px solid #DEDEDE",
    borderRadius: "5px",
    overflow: "hidden",
  },
  componentImage: { width: "100%", height: "100%", objectFit: "cover" },
  componentDetails: { minWidth: 0, gap: "6px", justifyContent: "center" },
  componentName: {
    ...TYPOGRAPHY_STYLES.sm.bold,
    color: theme.palette.text.primary,
    [theme.breakpoints.down("md")]: {
      overflow: "hidden",
      textOverflow: "ellipsis",
      whiteSpace: "nowrap",
      width: "100%",
    },
  },
  componentVariant: { ...TYPOGRAPHY_STYLES.xs.regular, color: "#27272A" },
  componentSummary: { ...TYPOGRAPHY_STYLES.xs.regular, color: "#707070" },
}));

export default useStyles;
