import { TYPOGRAPHY_STYLES } from "@/utils/constants/typography.constant";
import { makeStyles } from "tss-react/mui";
import { PRODUCT_GRID_BANNER_ASPECT_RATIO } from "./product-grid-banner.constants";

const useStyles = makeStyles({ name: "ProductGrid" })((theme) => ({
  root: {
    width: "100%",
  },
  gridContainer: {
    display: "grid",
    gridTemplateColumns: "repeat(4, minmax(0, 1fr))",
    gridAutoRows: "1fr",
    gridAutoFlow: "row dense",
    alignItems: "stretch",
    gap: 0,
    paddingBottom: theme.spacing(1),
    [theme.breakpoints.down("lg")]: {
      gridTemplateColumns: "repeat(2, 1fr)",
      gridAutoRows: "auto",
      gap: 0,
    },
  },
  bannerWrapper: {
    gridColumn: "1 / span 2",
    gridRow: "span 2",
    display: "flex",
    justifyContent: "stretch",
    alignSelf: "stretch",
    [theme.breakpoints.down("lg")]: {
      gridColumn: "span 2",
      gridRow: "span 1",
    },
  },
  bannerWrapperRight: {
    gridColumn: "3 / span 2",
    gridRow: "span 2",
    display: "flex",
    justifyContent: "stretch",
    alignSelf: "stretch",
    [theme.breakpoints.down("lg")]: {
      gridColumn: "span 2",
      gridRow: "span 1",
    },
  },
  bannerContent: {
    display: "flex",
    width: "100%",
    height: "100%",
    flexDirection: "column",
    justifyContent: "flex-end",
    alignItems: "flex-end",
    cursor: "pointer",
    overflow: "hidden",
    position: "relative",
    backgroundColor: "var(--product-image-background)",
    aspectRatio: PRODUCT_GRID_BANNER_ASPECT_RATIO.desktop,
    transition: "transform 0.9s ease",
    boxSizing: "border-box",
    border: "1px solid #E0E0E0",
    "&:hover .bannerCtaCount": {
      opacity: 0,
      maxWidth: 0,
      transform: "translateX(-8px) scaleX(0.85)",
    },
    "&:hover .bannerCtaText": {
      opacity: 1,
      maxWidth: 220,
      transform: "translateX(0) scaleX(1)",
    },
    [theme.breakpoints.down(1200)]: {
      width: "100%",
      height: "auto",
      aspectRatio: PRODUCT_GRID_BANNER_ASPECT_RATIO.tablet,
    },
    [theme.breakpoints.down("md")]: {
      aspectRatio: PRODUCT_GRID_BANNER_ASPECT_RATIO.mobile,
    },
  },
  bannerImage: {
    width: "100%",
    height: "100%",
    objectFit: "cover",
    position: "absolute",
    top: 0,
    left: 0,
    zIndex: 0,
  },
  bannerText: {
    position: "relative",
    zIndex: 2,
    color: "#fff",
    textAlign: "right",
  },
  bannerCta: {
    position: "absolute",
    right: 12,
    bottom: 12,
    zIndex: 2,
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    gap: 8,
    padding: "5.5px 12px",
    backgroundColor: "#fff",
    color: "#171717",
    ...TYPOGRAPHY_STYLES.md.regular,
    textAlign: "center",
    boxShadow: "0 2px 8px rgba(0, 0, 0, 0.15)",
    overflow: "hidden",
    transition: "gap 920ms cubic-bezier(0.22, 1, 0.36, 1)",
    "&:hover .bannerCtaCount": {
      opacity: 0,
      maxWidth: 0,
      transform: "translateX(-8px) scaleX(0.85)",
    },
    "&:hover .bannerCtaText": {
      opacity: 1,
      maxWidth: 220,
      transform: "translateX(0) scaleX(1)",
    },
  },
  bannerCtaCount: {
    display: "inline-block",
    flexShrink: 0,
    maxWidth: 28,
    overflow: "hidden",
    opacity: 1,
    transform: "translateX(0) scaleX(1)",
    transformOrigin: "left center",
    textAlign: "center",
    transition: "max-width 920ms cubic-bezier(0.22, 1, 0.36, 1), opacity 260ms ease, transform 320ms cubic-bezier(0.22, 1, 0.36, 1)",
    willChange: "max-width, opacity, transform",
    ...TYPOGRAPHY_STYLES["md"].regular,
  },
  bannerCtaText: {
    display: "inline-block",
    flexShrink: 1,
    maxWidth: 0,
    opacity: 0,
    overflow: "hidden",
    transform: "translateX(-8px) scaleX(0.92)",
    transformOrigin: "left center",
    whiteSpace: "nowrap",
    textAlign: "center",
    transition: "max-width 920ms cubic-bezier(0.22, 1, 0.36, 1), opacity 260ms ease, transform 320ms cubic-bezier(0.22, 1, 0.36, 1)",
    willChange: "max-width, opacity, transform",
    ...TYPOGRAPHY_STYLES["md"].regular,
  },
  productGrid: {
    display: "contents",
  },
  loadingProductCard: {
    padding: "16px",
    display: "flex",
    flexDirection: "column",
    gap: "16px",
    position: "relative",
    width: "100%",
    boxSizing: "border-box",
    borderTop: "1px solid #E0E0E0",
    borderBottom: "1px solid #E0E0E0",
    borderRight: "1px solid #E0E0E0",
    background: "#fff",
    [theme.breakpoints.down("md")]: {
      padding: "8px",
    },
  },
  loadingProductImage: {
    width: "100%",
    aspectRatio: "350 / 440",
  },
  loadingProductInfo: {
    display: "flex",
    flexDirection: "column",
    gap: "8px",
  },
  loadingProductName: {
    width: "80%",
    fontSize: "0.85rem",
  },
  loadingPriceRow: {
    display: "flex",
    gap: "8px",
    alignItems: "center",
  },
  loadingColorRow: {
    display: "flex",
    gap: "6px",
    alignItems: "center",
  },
  loadingColorDot: {
    borderRadius: 2,
  },
  drawerPaper: {
    width: 490,
    maxWidth: "100%",
    [theme.breakpoints.down("md")]: {
      width: "100vw",
    },
  },
  drawerHeader: {
    display: "flex",
    width: "100%",
    justifyContent: "space-between",
    alignItems: "center",
    gap: 10,
    alignSelf: "stretch",
    padding: "16px 20px",
    backgroundColor: "#f5f5f5",
    borderBottom: "1px solid #E0E0E0",
  },
  drawerTitle: {
    flex: "0 1 auto",
    ...TYPOGRAPHY_STYLES["xl"].bold,
    textTransform: "uppercase",
    color: "#1a1a1a",
  },
  drawerClose: {
    background: "none",
    border: "none",
    padding: 0,
    cursor: "pointer",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    color: "#1a1a1a",
  },
  drawerCloseIcon: {
    fontSize: 40,
    fontWeight: 300,
    color: "#2c2c2c",
    lineHeight: 1,
  },
  paginationWrapper: {
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    padding: "40px 0px",
  },
}));

export default useStyles;
