import { TYPOGRAPHY_STYLES } from "@/utils/constants/typography.constant";
import { makeStyles } from "tss-react/mui";

const useStyles = makeStyles({
  name: "NumberSpinner",
})((theme) => ({
  root: {
    display: "inline-flex",
    alignItems: "center",
    border: "none",
    boxShadow: "none",
  },
  button: {
    display: "flex",
    width: 32,
    height: 32,
    minWidth: 22,
    minHeight: 22,
    padding: 8,
    justifyContent: "center",
    alignItems: "center",
    gap: 10,
    aspectRatio: "1/1",
    border: "1px solid #d9d9d9",
    borderRadius: 0,
    background: "#fff",
    cursor: "pointer",
    boxShadow: "none",
    color: theme.palette.text.primary,
    fontSize: 16,
    transition: "background 0.2s, border 0.2s",
    "&:hover": {
      background: "#f5f5f5",
      borderColor: "#bfbfbf",
    },
    "&.Mui-disabled": {
      background: theme.palette.action.disabledBackground,
      color: theme.palette.text.disabled,
      borderColor: theme.palette.action.disabledBackground,
      cursor: "not-allowed",
      opacity: 0.6,
    },
    [theme.breakpoints.down("sm")]: {
      width: 24,
      height: 24,
      padding: 4,
    },
  },
  miniCartButton: {
    display: "flex",
    width: 22,
    height: 22,
    minWidth: 22,
    minHeight: 22,
    padding: 8,
    justifyContent: "center",
    alignItems: "center",
    gap: 10,
    aspectRatio: "1/1",
    border: "1px solid #d9d9d9",
    borderRadius: 0,
    background: "#fff",
    cursor: "pointer",
    boxShadow: "none",
    color: theme.palette.text.primary,
    fontSize: 16,
    transition: "background 0.2s, border 0.2s",
    "&:hover": {
      background: "#f5f5f5",
      borderColor: "#bfbfbf",
    },
    "&.Mui-disabled": {
      background: theme.palette.action.disabledBackground,
      color: theme.palette.text.disabled,
      borderColor: theme.palette.action.disabledBackground,
      cursor: "not-allowed",
      opacity: 0.6,
    },
    [theme.breakpoints.down("sm")]: {
      width: 22,
      height: 22,
      padding: 4,
    },
  },
  input: {
    width: 50,
    maxHeight: 32,
    textAlign: "center",
    font: `400 16px${theme.typography.fontFamily} !important`,
    border: "none",
    outline: "none !important",
    background: "transparent !important",
    margin: "0",
    padding: 0,
    color: theme.palette.text.primary,
    boxShadow: "none",
    WebkitAppearance: "none",
    MozAppearance: "textfield",
    "& .MuiOutlinedInput-input": {
      padding: "0",
      textAlign: "center",
      font: `400 16px${theme.typography.fontFamily} !important`,
      ...TYPOGRAPHY_STYLES.sm.regular,
    },
    "& .MuiOutlinedInput-notchedOutline": {
      border: "none",
    },
    "& .MuiInputBase-input": {
      border: "none",
    },
    "& .MuiOutlinedInput-root.Mui-focused .MuiOutlinedInput-notchedOutline": {
      border: "none !important",
      boxShadow: "none",
    },
    [theme.breakpoints.down("sm")]: {
      width: 27,
      height: 24,
      padding: 4,
    },
  },
  miniCartInput: {
    width: 28,
    maxHeight: 22,
    textAlign: "center",
    // font: `500 14px ${theme.typography.fontFamily} !important`,
    border: "none",
    outline: "none !important",
    background: "transparent !important",
    margin: "0",
    padding: 0,
    color: "#27251F",
    boxShadow: "none",
    WebkitAppearance: "none",
    MozAppearance: "textfield",
    paddingBlock: 0,
    ...TYPOGRAPHY_STYLES.sm.regular,
    "& .MuiOutlinedInput-input": {
      padding: "0",
      textAlign: "center",
      color: "#27251F",
    },
    "& .MuiOutlinedInput-notchedOutline": {
      border: "none",
    },
    "& .MuiInputBase-input": {
      border: "none",
    },
    "& .MuiOutlinedInput-root.Mui-focused .MuiOutlinedInput-notchedOutline": {
      border: "none !important",
      boxShadow: "none",
    },
    [theme.breakpoints.down("sm")]: {
      width: 28,
      height: 22,
      padding: 4,
    },
  },
  buttonGroup: {
    display: "flex",
    alignItems: "center",
    gap: 0,
  },
}));

export default useStyles;
