import { TYPOGRAPHY_STYLES } from "@/utils/constants/typography.constant";
import { makeStyles } from "tss-react/mui";

export const cartMiniItemImage = {
  width: 88,
  height: 100,
} as const;

const useStyles = makeStyles({ name: "CartItemComponent" })((theme) => ({
  root: {
    width: "100%",
    padding: "16px 0",
    borderBottom: `1px solid ${theme.palette.divider}`,
    display: "flex",
    flexDirection: "column",
    gap: 10,
  },
  rootLast: {
    width: "100%",
    padding: "16px 0",
    display: "flex",
    flexDirection: "column",
    gap: 10,
  },
  outOfStockRoot: {
    opacity: 0.56,
  },
  mainRow: {
    width: "100%",
    display: "grid",
    gridTemplateColumns: "88px minmax(0, 1fr) minmax(0, max-content)",
    gap: 12,
    alignItems: "start",
  },
  imageBox: {
    width: 88,
    height: 100,
    backgroundColor: "var(--product-image-background)",
    display: "block",
  },
  image: {
    width: 88,
    height: 100,
    objectFit: "cover",
  },
  productImageLink: {
    display: "block",
    width: "100%",
    height: "100%",
    color: "inherit",
    textDecoration: "none",
  },
  infoCol: {
    minWidth: 0,
    display: "flex",
    flexDirection: "column",
    gap: 4,
  },
  name: {
    ...TYPOGRAPHY_STYLES.base.bold,
    lineHeight: "140%",
    marginBottom: 2,
  },
  productNameLink: {
    display: "block",
    color: "inherit",
    textDecoration: "none",
  },
  detailLine: {
    ...TYPOGRAPHY_STYLES.sm.regular,
    lineHeight: "140%",
    fontSize: 12,
    wordBreak: "break-word",
  },
  sizeLine: {
    ...TYPOGRAPHY_STYLES.sm.regular,
  },
  actionRow: {
    marginTop: 4,
    display: "flex",
    alignItems: "center",
    gap: 6,
    flexWrap: "nowrap",
    ...TYPOGRAPHY_STYLES.sm.regular,
  },
  actionButton: {
    ...TYPOGRAPHY_STYLES.sm.regular,
    color: theme.palette.grey[500],
    textDecoration: "underline",
    cursor: "pointer",
    background: "none",
    border: 0,
    padding: 0,
    whiteSpace: "nowrap",
    transition: "color 0.2s",
    "&:hover": {
      color: theme.palette.primary.dark,
    },
  },
  actionDivider: {
    ...TYPOGRAPHY_STYLES.sm.regular,
    color: theme.palette.text.disabled,
    userSelect: "none",
  },
  quantityCol: {
    display: "none",
  },
  quantityControl: {
    display: "flex",
    alignItems: "center",
    justifyContent: "flex-start",
    gap: 8,
    marginTop: 6,
  },
  quantityButton: {
    width: 24,
    height: 24,
    padding: 4,
    border: `1px solid ${theme.palette.divider}`,
    borderRadius: 4,
    color: theme.palette.text.primary,
    fontSize: 16,
    background: theme.palette.background.paper,
    "&:disabled": {
      color: theme.palette.text.disabled,
      borderColor: theme.palette.action.disabledBackground,
      background: theme.palette.action.disabled,
    },
  },
  quantityText: {
    ...TYPOGRAPHY_STYLES.base.bold,
    minWidth: 16,
    textAlign: "center",
    color: theme.palette.text.primary,
  },
  helperText: {
    ...TYPOGRAPHY_STYLES.sm.regular,
    color: "#d32f2f",
    textAlign: "left",
    paddingTop: 4,
  },
  priceCol: {
    display: "flex",
    flexDirection: "column",
    alignItems: "flex-end",
    marginTop: 2,
    minWidth: 0,
  },
  currentPrice: {
    ...TYPOGRAPHY_STYLES.sm.bold,
    color: theme.palette.text.primary,
    lineHeight: "140%",
    whiteSpace: "nowrap",
  },
  originalPriceRow: {
    marginTop: 2,
    display: "flex",
    alignItems: "center",
    gap: 6,
  },
  originalPrice: {
    ...TYPOGRAPHY_STYLES.xs.regular,
    color: theme.palette.text.disabled,
    textDecoration: "line-through",
    whiteSpace: "nowrap",
    lineHeight: "normal",
  },
  removeButton: {
    width: 32,
    height: 32,
    justifySelf: "end",
    alignSelf: "end",
    marginTop: 8,
    "&:hover": {
      color: theme.palette.error.dark,
    },
  },
  rightCol: {
    minWidth: 0,
    width: "max-content",
    maxWidth: "100%",
    display: "flex",
    flexDirection: "column",
    alignItems: "flex-end",
    justifyContent: "space-between",
    height: "100%",
  },
  attachedStack: {
    width: "100%",
  },
  attachedRow: {
    marginLeft: 24,
    paddingTop: 4,
    gap: 12,
    alignItems: "flex-start",
  },
  attachedImageBox: {
    width: 68,
    height: 88,
    overflow: "hidden",
    border: `1px solid ${theme.palette.divider}`,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "var(--product-image-background)",
    gap: 16,
  },
  attachedImage: {
    width: "68px",
    height: "88px",
    objectFit: "cover",
  },
  attachedInfoCol: {
    minWidth: 0,
    display: "flex",
    flexDirection: "column",
    gap: 4,
  },
  attachedBadge: {
    ...TYPOGRAPHY_STYLES.sm.bold,
    width: "fit-content",
    padding: "2px 8px",
    borderRadius: 999,
    color: theme.palette.common.white,
    backgroundColor: theme.palette.primary.main,
    lineHeight: "140%",
    marginBottom: 4,
  },
  attachedName: {
    ...TYPOGRAPHY_STYLES.base.bold,
    color: theme.palette.text.primary,
    lineHeight: "140%",
    marginBottom: 0,
    [theme.breakpoints.down("md")]: {
      overflow: "hidden",
      textOverflow: "ellipsis",
      whiteSpace: "nowrap",
      width: "100%",
    },
  },
  attachedSubInfo: {
    ...TYPOGRAPHY_STYLES.sm.regular,
    color: theme.palette.text.secondary,
    lineHeight: "140%",
  },
  attachedSizeLine: {
    ...TYPOGRAPHY_STYLES.sm.regular,
    color: theme.palette.text.secondary,
    lineHeight: "140%",
  },
  attachedActionButton: {
    marginTop: 4,
    ...TYPOGRAPHY_STYLES.sm.bold,
    color: theme.palette.primary.main,
    textDecoration: "underline",
    background: "none",
    border: 0,
    padding: 0,
    width: "fit-content",
    cursor: "pointer",
    fontFamily: "inherit",
    transition: "color 0.2s",
    "&:hover": {
      color: theme.palette.primary.dark,
    },
  },
  attachedQuantity: {
    ...TYPOGRAPHY_STYLES.base.bold,
    color: theme.palette.text.primary,
    minWidth: "fit-content",
    textAlign: "left",
    marginTop: 2,
  },
  attachedPriceCol: {
    display: "flex",
    flexDirection: "column",
    alignItems: "flex-start",
    paddingRight: 40,
    gridColumn: "2 / 3",
    minWidth: 0,
  },
}));

export default useStyles;
